### ISSUE TITLE
Error: mvt-android download-apks --output

### ISSUE THREAD

**Issue by SnaSana111** [mvt-project/mvt#51]
Hello,

   So I'm not a develop and I need some help trying to debug my phone. I currently have my android in developer mode with USB debugging enabled. I downloaded Xcode and Homebrew on my MacBook Pro using the terminal and everything was fine until I tried to run the mvt-android code. When I try to run this code

mvt-android download-apks --output /path/to/folder

I just see" quote " in the terminal and I don't know what it's asking me to enter. I keep checking the folder that I created to store the APKs but nothing has been added to it. 

What am I doing wrong?

**Comment by SnaSana111** [comment]
Also, my Mac is not recognizing my android device so I can't connect it to my computer it being an android. I read online that you can use Android File Transfer to look at the files on the device. I can connect my phone using only Android File Transfer. However, I would like to know how to download the APKs for debugging from there and run the codes that look for the hash. Please help!!!!

**Comment by arayofcode** [comment]
I faced this error too. If you receive this error, you either need to install adb or if it is installed, you have not enabled USB Debugging. To install adb, run the following commands depending on your distribution.

For Ubuntu/ Debian,

```bash
sudo apt-get install android-tools-adb
```

For Fedora/ SUSE-based Linux, 

```bash
sudo yum install android-tools
```

To check if this has been installed correctly, connect your phone to the computer using USB cable, and run 
```bash
adb devices
```
It should display your device. 

Sometimes it doesn't show anything. In that case, enable dev tools and USB debugging. You'll get a notification on your phone about exchanging keys. Accept it and then run `adb devices`. This will work

**Comment by mfrederick98** [comment]
So my download_apk method ran...observations.
1.) though it downloaded 300 apks from my Lineageos 17 pixel 3XL, many permission denied or exception path not found  or unable to download file 

messages during the process on obscure android apps that are known safe
2.) can you interrupt the scan results attached?

![Screenshot 2021-07-22 021835-totalvirus](https://user-images.githubusercontent.com/8031924/126597167-af9bb048-a264-40fe-ab2e-c658089b4160.jpg)

![Screenshot 2021-07-22 021928-koodous](https://user-images.githubusercontent.com/8031924/126597267-91a04c8b-36ff-481e-93c5-f9fe04c32afb.jpg)

**Comment by mfrederick98** [comment]
Just to confirm on my inquiry...anything but yes is good Detected for koodous scan.  Just curious what the totalvirus 0/71-0/75 values represent.

**Comment by goshawk22** [comment]
> 1.) though it downloaded 300 apks from my Lineageos 17 pixel 3XL, many permission denied or exception path not found or unable to download file
> 
> messages during the process on obscure android apps that are known safe

#20 should fix this

**Comment by SnaSana111** [comment]
Hello, 

can anyone help me with my issues?

Thanks...

**Comment by SnaSana111** [comment]
So after I connect my android to my MacBook and run the mvt-android command in terminal this is what it gives me. I don't know what it wants me to enter.

<img width="571" alt="Quote?" src="https://user-images.githubusercontent.com/78973147/126697822-5dbbb0d2-bcfb-4f1c-be3d-4c8a5f7fee4e.png">

**Comment by SnaSana111** [comment]
Also, my android is in debugging mode but I don't see the android in finder. I would appreciate some pointers as to what I can do next. 

Thanks!

**Comment by arayofcode** [comment]
> So after I connect my android to my MacBook and run the mvt-android command in terminal this is what it gives me. I don't know what it wants me to enter.
> 
> <img alt="Quote?" width="571" src="https://user-images.githubusercontent.com/78973147/126697822-5dbbb0d2-bcfb-4f1c-be3d-4c8a5f7fee4e.png">

You forgot to put a space after `--output`. Also, the path has spaces so you can keep it in quotes. Here's what your command should look like:

```bash
mvt-android download-apks --output "/FBI's Macbook/Macintosh HD/Users/gobblinggargoyle/Desktop/MVTAKPs". In case of typos, please correct accordingly. 
```

**Comment by Te-k** [comment]
> Just to confirm on my inquiry...anything but yes is good Detected for koodous scan. Just curious what the totalvirus 0/71-0/75 values represent.

The 0/71 is the results from VirusTotal check

**Comment by Te-k** [comment]
> So after I connect my android to my MacBook and run the mvt-android command in terminal this is what it gives me. I don't know what it wants me to enter.
> 
> <img alt="Quote?" width="571" src="https://user-images.githubusercontent.com/78973147/126697822-5dbbb0d2-bcfb-4f1c-be3d-4c8a5f7fee4e.png">

You need to put your file path between double quotes because it contains spaces and simple quotes

**Comment by Te-k** [comment]
I think @arayofcode has answered to the main question here, so I am closing the ticket

**Comment by SnaSana111** [comment]
So, I put a space after --output . It still asks me to, I'm still getting the quote again. I don't know what it wants me to enter. 

On a separate note, I have also been trying to see if I can extract the backup of my phone to see if I can check that but I'm unable to extract the entire backup using Android Backup Extractor. One thing that I did find under Backups>System Config.  was a file .cuid2 which I feel indicates the presence of spyware on my phone (potentially [Pegasus).]
<img width="621" alt="cuid2" src="https://user-images.githubusercontent.com/78973147/127233616-63e41711-bd0e-4b61-92c0-720d3ba9695e.png">

I can't copy this file to my computer. When I try, it shows that it is copying it but it doesn't appear anywhere. I can copy other files from Android Backup Extractor easily and they do appear on my computer. Just not this one 

 I'm also still struggling to use the instructions to do a thorough analysis of my phone. I'm feeling a little lost at this point.

**Comment by SnaSana111** [comment]
Also, there is no other backup folder that I can copy onto my computer so it's proving a little more challenging to find what I need.

**Comment by Te-k** [comment]
> So, I put a space after --output . It still asks me to, I'm still getting the quote again. I don't know what it wants me to enter.

Which quote?

> On a separate note, I have also been trying to see if I can extract the backup of my phone to see if I can check that but I'm unable to extract the entire backup using Android Backup Extractor. 

A successful backup should give you a `.ab` file that you can then analyze with `mvt-android check-backup` (only SMS will be analyzed)

**Comment by SnaSana111** [comment]
> > So, I put a space after --output . It still asks me to, I'm still getting the quote again. I don't know what it wants me to enter.
> 
> Which quote?
> 
> > On a separate note, I have also been trying to see if I can extract the backup of my phone to see if I can check that but I'm unable to extract the entire backup using Android Backup Extractor.
> 
> A successful backup should give you a `.ab` file that you can then analyze with `mvt-android check-backup` (only SMS will be analyzed)

So, when I try to back up my android. It backsup to the Google Drive and I can't download it from there. I have a Motorola z4 and that's the only option I have to do a backup. I've been thinking about using a third-party software to do a backup but I'm not sure which one would be best. 

When I use Android Backup Extractor, it just shows me all the files I have on my phone. I don't see any option that allows me to generate .ab file.

I'm planning to keep trying this week to see if I can get a bit further with this.

**Comment by SnaSana111** [comment]
So my phone sustained some water damage today and I'm trying to salvage it now. Will have to see if it works in 2-3 days and then continue.

**Comment by botherder** [comment]
Closing this ticket as it derailed in off topic.
